/**
 * Shared read-only view over a RawScrape, built once and handed to every
 * transform sub-function. Keeps each sub-function free of re-derivation logic.
 */

import type { ParsedPage, RawScrape } from "@/types/scrape";
import type { PageType, Snippet } from "@/types/knowledge";
import { primaryPageType } from "@/lib/discovery/classify";
import { isNonEmpty, visibleText } from "@/lib/utils/text";

export type TransformContext = {
  raw: RawScrape;
  pages: ParsedPage[];
  homepage: ParsedPage | null;
  /** All JSON-LD nodes from every page, concatenated. */
  jsonLd: Record<string, unknown>[];
};

export function buildContext(raw: RawScrape): TransformContext {
  const homepage =
    raw.pages.find((page) => page.pageTypes.includes("homepage")) ?? raw.pages[0] ?? null;

  return {
    raw,
    pages: raw.pages,
    homepage,
    jsonLd: raw.pages.flatMap((page) => page.structuredData.jsonLd),
  };
}

/** Pages that serve a given category, in the order they were crawled. */
export function pagesOfType(context: TransformContext, pageType: PageType): ParsedPage[] {
  return context.pages.filter((page) => page.pageTypes.includes(pageType));
}

/**
 * Is this text a passage, or a fragment of page furniture?
 *
 * This is the one place a length rule is applied to snippet text, and it is
 * worth being precise about why it does not contradict §8's "the scraper does
 * not judge quality".
 *
 * The rule is **structural, not qualitative.** A Category 2 snippet is supposed
 * to be a passage of narrative that an LLM or a reviewer can read and condense.
 * A single word cannot be one, whatever its quality. Readability's paragraph
 * extraction pulls `p`, `li` and `blockquote`, and a themed nav rendered as a
 * list gives it `<li>Shop</li>` — which arrived in Overview and Pitch as a
 * snippet reading, in full, "Shop".
 *
 * Two words and twelve visible characters, deliberately low:
 *
 *   - "Shop", "Ocean", "Biomes"        → out. Nav labels, not passages.
 *   - "Free shipping"                  → in. Two words, thirteen characters.
 *   - "MEET THE PICNIC PALS"           → in. A real hero heading.
 *
 * Anything above that floor is still bundled verbatim with no readability score
 * and no filler detection — a short, plain sentence is exactly the kind of copy
 * a small business writes, and judging it is the reviewer's job.
 */
export function isSubstantiveSnippet(text: string): boolean {
  const visible = visibleText(text);
  if (visible.length < 12) return false;
  return visible.split(/\s+/).filter(Boolean).length >= 2;
}

/**
 * Every text block a page offers, in reading order, tagged with provenance.
 *
 * **The single gathering point for Category 2 evidence.** Every narrative field
 * reaches page text through here or through `allSnippets`, which is a fold over
 * it, so a rule added here applies to all of them at once. `industryOutlook`
 * used to map `page.paragraphs` itself and was the exact hazard this comment
 * exists to prevent — a second copy of the gathering logic that quietly misses
 * every fix the shared one receives. `scripts/smoke.ts` asserts no transform
 * module reads `.paragraphs` directly.
 */
export function pageSnippets(page: ParsedPage): Snippet[] {
  const source = primaryPageType(page.pageTypes);
  return page.paragraphs
    .filter(isNonEmpty)
    .filter(isSubstantiveSnippet)
    .map((text) => ({
      source,
      sourceUrl: page.url,
      text: visibleText(text),
    }));
}

export function allSnippets(context: TransformContext): Snippet[] {
  return context.pages.flatMap(pageSnippets);
}

/**
 * Does this text look like it was cut off by a character limit rather than
 * finished?
 *
 * Overview and Pitch both fall back to `og:description` / `meta description`,
 * and those are routinely generated by truncating body copy at ~155 characters
 * — mid-word, with no regard for sentence boundaries. A real scan of a Shopify
 * store produced: *"…They're soft, weird, cuddly, and ful..."*
 *
 * Nothing in this pipeline truncates anything; that string is the site's own
 * meta description, reproduced faithfully. Which is the point — the fix cannot
 * be "truncate on a word boundary", because we are not the ones truncating, and
 * repairing the missing characters would mean inventing them.
 *
 * What we can do is stop treating a self-truncated description as the *best*
 * evidence available when whole paragraphs exist. Same shape as the Year Founded
 * ranking: collect everything, rank once, keep the loser visible.
 */
export function looksTruncated(text: string): boolean {
  const trimmed = visibleText(text);
  if (/(\.\.\.|…)$/.test(trimmed)) return true;
  // The classic meta-description cut: right around the limit, ending on a bare
  // word with no terminal punctuation.
  return trimmed.length >= 150 && /[\p{L}\p{N}]$/u.test(trimmed);
}

/**
 * The site's own one-line self-description, if it published one.
 *
 * Shared by Overview and Pitch rather than written twice — they are different
 * fields but this is the same sentence, and the truncation handling has to be
 * identical or the same bug reappears on whichever one was not fixed.
 */
export function declaredDescription(
  context: TransformContext,
): { snippet: Snippet; truncated: boolean } | null {
  const homepage = context.homepage;
  if (!homepage) return null;

  const declared =
    homepage.structuredData.openGraph["og:description"] ??
    homepage.structuredData.meta["description"];
  if (!isNonEmpty(declared)) return null;

  const text = visibleText(declared);
  return {
    snippet: { source: "homepage", sourceUrl: homepage.url, text },
    truncated: looksTruncated(text),
  };
}

/**
 * Declared description plus page prose, ordered by how usable each is.
 *
 * A complete self-description leads: it is the site saying in one sentence what
 * it is. A *truncated* one goes last instead — still kept, because on a thin
 * site it may be the only self-description there is, but no longer the first
 * thing a reviewer reads and no longer the passage most likely to be condensed
 * into the final value.
 */
export function describedSnippets(context: TransformContext, prose: Snippet[]): Snippet[] {
  const declared = declaredDescription(context);
  if (!declared) return prose;
  return declared.truncated
    ? [...prose, declared.snippet]
    : [declared.snippet, ...prose];
}

/* ------------------------------------------------------------------ *
 * The Overview / Pitch pool
 * ------------------------------------------------------------------ */

/**
 * Where a passage came from, for ranking purposes. Not the same as `PageType`:
 * a homepage `h1` and a homepage paragraph are the same page and very different
 * evidence.
 */
export type PositioningKind = "about" | "hero" | "homepage-prose" | "declared";

export type PositioningCandidate = { kind: PositioningKind; snippet: Snippet };

/**
 * Every passage that could support Overview or Pitch, gathered once.
 *
 * These two fields used to build separate pools, and each pool had a blind spot
 * the other did not:
 *
 *   - **Overview** returned About-page prose and stopped. `if (fromAbout.length
 *     > 0) return fromAbout;` — so on any site with an About page, Overview never
 *     saw the homepage or the declared description at all. A thin About page
 *     starved the field while a rich homepage sat unread.
 *   - **Pitch** was the mirror image: homepage first, About only as a fallback
 *     when the homepage yielded literally nothing.
 *
 * That split also contradicted the prompt these fields feed.
 * `prompts/02-overview-pitch.md` takes a **single** `snippets` array and writes
 * both fields from it, specifically so they can be written to differ from each
 * other. Two divergent bundles cannot be passed to a prompt that accepts one.
 *
 * So the pool is shared and the *ordering* is per-field. Neither field can miss
 * evidence the other found; each still leads with what suits it. See
 * `orderPositioning`.
 */
export function positioningPool(context: TransformContext): PositioningCandidate[] {
  const candidates: PositioningCandidate[] = [];

  for (const page of pagesOfType(context, "about")) {
    for (const snippet of pageSnippets(page)) candidates.push({ kind: "about", snippet });
  }

  const homepage = context.homepage;
  if (homepage) {
    // The hero: an h1/h2 plus the copy around it is where a site makes its
    // pitch. Kept as its own kind rather than folded into homepage prose,
    // because it is the single most persuasive string on most sites and the
    // single least factual — the two fields want it at opposite ends.
    const hero = homepage.headings.find((heading) => heading.level <= 2);
    if (hero && isSubstantiveSnippet(hero.text)) {
      candidates.push({
        kind: "hero",
        snippet: { source: "homepage", sourceUrl: homepage.url, text: visibleText(hero.text) },
      });
    }
    for (const snippet of pageSnippets(homepage).slice(0, 3)) {
      candidates.push({ kind: "homepage-prose", snippet });
    }
  }

  const declared = declaredDescription(context);
  if (declared) candidates.push({ kind: "declared", snippet: declared.snippet });

  return candidates;
}

/**
 * Overview is third-person and factual, so About prose leads and the hero
 * slogan trails. Pitch is second-person and persuasive, so the ordering
 * inverts. Everything else sits between, identically for both.
 *
 * Expressed as a priority over *kinds* rather than as two hand-written
 * orderings, so the difference between the fields is one line of data and
 * cannot drift into two divergent implementations again.
 */
const OVERVIEW_PRIORITY: PositioningKind[] = ["about", "declared", "homepage-prose", "hero"];
const PITCH_PRIORITY: PositioningKind[] = ["hero", "declared", "homepage-prose", "about"];

export function orderPositioning(
  context: TransformContext,
  field: "overview" | "pitch",
): Snippet[] {
  const priority = field === "overview" ? OVERVIEW_PRIORITY : PITCH_PRIORITY;
  const pool = positioningPool(context);

  // A declared description the site truncated mid-word goes last whatever the
  // field's priority says — it is the site's own words, so it is kept, but it is
  // not the passage either field should be condensing first. Same rule as
  // `describedSnippets`, which still serves Writing Style.
  const truncated = declaredDescription(context)?.truncated === true;
  const rank = (candidate: PositioningCandidate) =>
    candidate.kind === "declared" && truncated
      ? priority.length
      : priority.indexOf(candidate.kind);

  return pool
    .map((candidate, index) => ({ candidate, index }))
    // Index as the tiebreak keeps document order within a kind — a stable sort
    // by hand, because Array.prototype.sort's stability is guaranteed but the
    // comparator has to not fight it.
    .sort((a, b) => rank(a.candidate) - rank(b.candidate) || a.index - b.index)
    .map((entry) => entry.candidate.snippet);
}
